### ISSUE TITLE
Developed Rpackage for building the folder structure in working directory

### ISSUE THREAD

**Issue by DrMattG** [LivingNorway/TheDataPackage#1]
Linking back to my github page where I have added package with one function (so far) to build folder structure in users working directory. I have added a quick list of metadata in an rmarkdown template that will eventually become the minimum meta data file - my idea is to automatically create this file in the correct folder (perhaps other templates are needed in the other folders as we go on). I am keeping this separate at the moment as it is probably too technical a solution to what is fundamentally a manual (albeit with tools to guide) process, if we think it should be integrated at a later stage then it can be.

https://github.com/DrMattG/DataLegacyR/blob/master/R/build_folder_structure.R
https://github.com/DrMattG/DataLegacyR/blob/master/rmarkdown/templates/Minimum_meta_data.Rmd

**Comment by andersfi** [comment]
The more I think about this, the more I realize that I actually myself would like to have a set of R functions to manage my data archive. Not only help with organizing folders and metadata. A set of functions (or package) could easily be embedded in a shiny app also. Some ideas for functionality:

* Build metadata file(s) - maybe we should think about the possibility for generating one plain text file for metadata (e.g. .md, .txt, or .rtf - I would personally prefer .md) and one meta.xml file in EML? Rationale; The .xml file is machine-readable and what goes into a DwC-A, but impossible for human consumption without translation. It would be cool to be able to build metadata based upon information in files (possible from templates coming from DataEntryForms) directly - would save some time indeed, but could come at some later stage.
* Build folder structure (as noted below)
* Build (and rebuild, upon request) indexes of files held in the different folders. Each folder should contain a README file with a description of content - importantly a list of files, their formats (if not obvious from the extension), created and last modified by whom, and the relationship between files. Although the content description in most cases still would have to be a manual job, I find this process of listing the content of folders a rather boring and tedious job that could be sped up by doing part of it semi-automated.
* Sync your data-package with a data archive. This functionality would have to be restricted to some archives with good APIs off course. As most data repros I know about do not accept folder structures, the entire data package (minus metadata) should probably be stacked into a .zip archive. Then we are very close to what we do when working with GitHub trough R studio - which is fine. 
* ....

**Comment by DrMattG** [comment]
I'll close this issue and open three new issues that correspond to your points here so that we can use them as a list of aims
