### ISSUE TITLE
folder name-convention

### ISSUE THREAD

**Issue by andersfi** [LivingNorway/TheDataPackage#18]
proposal to change the naming of sub-folders under the /data folder to the following:

/raw
/scan
/derived
/dwc-a

**Rational**
* skip the _data suffix in order to save space, it should be implicitly clear that everything under the data folder is data anyway
* the folder named "mapped_data" is sort of ambiguous, as there theoretically always is some kind of mapping for any data. However, it is usually a raw and derived representative of any dataset. 
* get a separate folder for the dwc-a files, including metadata in eml.

**Comment by DrMattG** [comment]
@andersfi how does this look? 
![image](https://user-images.githubusercontent.com/11541781/85004038-597f2f80-b157-11ea-96d4-ff3767ae4210.png)

**Comment by DrMattG** [comment]
The dwc-a file will be populated with other files as the workflow progresses

**Comment by andersfi** [comment]
Very nice (= 
Perhaps put a hypen in the dwc-a folder name according to convention?

**Comment by DrMattG** [comment]
https://github.com/LivingNorway/LivingNorwayR/pull/12
